### ISSUE TITLE
The Temperature Feels Like sensor does not have long term statistics

### ISSUE THREAD

**Issue by sergeykad** [Limych/ha-apparent-temperature#118]
**Environment**

- Home Assistant Core release with the issue:  2023.7.3 and earlier versions
- This custom component release with the issue: 0.3.7
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): VM

**Describe the bug**
Cannot add a graph tith the sensor's reading to dushboard. The sensor does not show up in the "Statistics Graph Card Configuration" card configuration. According to the information in the card [long term statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics) are missing.

I can add the sensor to the Gauge graph.

**Configuration.yaml**
```yaml
sensor:
  - platform: temperature_feels_like
    source:
      - sensor.tze200_9yapgbuv_ts0601_temperature
      - sensor.tze200_9yapgbuv_ts0601_humidity
```

**Steps to Reproduce**
Go to "Edit Dashboard" and try adding Statistics Graph card with the sensor.

**Expected behavior**
The sensors shows up in sensors list of the Statistics Graph card.

**Debug log**

```text

Add your logs here.

```

**Additional context**
