### ISSUE TITLE
Bug: Incompatibility with Home Assistant 2024.1.2 - Disrespects Unit Preference Imperial/Metric

### ISSUE THREAD

**Issue by jrstubbington** [Limych/ha-apparent-temperature#138]
Note: This is not a feature request - bug template not available.

### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

After updating to HA 2024.1.2, this plugin no longer seems to respect the unit set in home assistant. Worked perfectly fine before in two circumstances:

1. Indoor - internal temperature with internal humidity sensor
2. Outdoor - using weather forecast

configuration.yml
```yaml
  - platform: temperature_feels_like
    source: weather.forecast_home

  - platform: temperature_feels_like
    name: "Bedroom Feels Like Temperature"
    source:
      - sensor.everything_presence_one_7e9e1c_temperature
      - sensor.everything_presence_one_7e9e1c_humidity
```

Indoor:
![image](https://github.com/Limych/ha-temperature-feels-like/assets/10409281/f57c6803-2f32-4d9e-861a-b67d0f8ee47e)

Outdoor (Apparently, everyone outdoors is being boiled alive):
![image](https://github.com/Limych/ha-temperature-feels-like/assets/10409281/725b9539-9ccd-4c25-9b3f-25e802282598)

Entity States:
![image](https://github.com/Limych/ha-temperature-feels-like/assets/10409281/1d0455f4-c68b-495e-8ba8-73f60418bcde)

System Settings:
![image](https://github.com/Limych/ha-temperature-feels-like/assets/10409281/9bc9adb4-5014-4711-9ea1-1ab48140a488)

Home Assistant Versions:
![image](https://github.com/Limych/ha-temperature-feels-like/assets/10409281/866715cf-c82d-4631-b9de-4ed38f199799)

### Describe the solution you'd like

I would like this to respect the selection of the unit as it did previously

### Describe alternatives you've considered

Attempted to reset and set my unit preference without success
Tried installing/reinstalling without success

### Additional context

None
