### ISSUE TITLE
Calculation error if wind value is not available

### ISSUE THREAD

**Issue by MagicalCrib** [Limych/ha-apparent-temperature#53]
**Describe the bug**
I'm using a weather entity to calculate the feels like temperature, but sometimes the Wind bearing is empty. In these cases, the calculation fails and I get "Unknown" result.

Is it possible to validate the wind availability? If Wind is present, compute as expected, otherwise compute with Temperature and Humidity only.

**Configuration.yaml**
```yaml
  - platform: temperature_feels_like
    name: "Home Feels Like Temperature"
    source: 
      - weather.home
```

**Debug log**
```Logger: custom_components.temperature_feels_like.sensor
Source: custom_components/temperature_feels_like/sensor.py:314
Integration: temperature_feels_like (documentation, issues)
First occurred: 18:16:01 (2 occurrences)
Last logged: 18:16:01
Can't calculate sensor value: some sources are unavailable.
```
