### ISSUE TITLE
Can't use `Independent Temperature and Humidity Entities`

### ISSUE THREAD

**Issue by sneakythr0ws** [Limych/ha-apparent-temperature#82]
Hi! 
```
can not read a block mapping entry; a multiline key may not be an implicit key at line 34, column 11:
        source:
              ^
```

```
sensor:
  - platform: temperature_feels_like
    name: 'Room temperature feels like'
    source:
      - sensor.ble_temperature_climate_sensor
      - sensor.ble_humidity_climate_sensor
```
