### ISSUE TITLE
More documentation on "source"

### ISSUE THREAD

**Issue by garithd** [Limych/ha-apparent-temperature#9]
Could you provide some examples of what "source" could look like if someone would want to use a few 'sensor's?

I intend to use a single outside sensor for humidity and then calculate a bedroom "feel like temp" in our house based on a sensor in the room (in celcius). My current config:

```
sensor:
  - platform: temperature_feels_like
    name: "Alex Room Feels Like Temp"
    source:
      - sensor.outside_humidity
      - sensor.alex_room_heater_ds18b20_temperature
```

This current config results in the sensor showing "unknown" in Developer Tools.

The output of in Developer Tools of the two "source" sensors are:

```
sensor.alex_heater_ds18b20_temperature | 22.6 | unit_of_measurement: °C friendly_name: Alex Heater DS18B20 Temperature device_class: temperature
```
and:
```
sensor.outside_humidity | 43 | friendly_name: outside_humidity
```

**Comment by Limych** [comment]
Please specify what kind of examples you are interested in.

In your case, the sensor was unable to recognize the humidity sensor because your humidity sensor did not have the appropriate class or unit of measurement. And without data on humidity, the calculation algorithm cannot work.

I made some changes to the code and now the humidity sensor is recognized also by the word "humidity" in the entity ID.

**Comment by Limych** [comment]
Separately, I note that using an outdoor humidity sensor to calculate the indoor temperature feels like is incorrect. Indoor humidity will differ from outdoor humidity. And this will affect the perception of temperature.

For correct calculations, it is necessary to have an indoor humidity sensor.

**Comment by garithd** [comment]
You're right, I hadn't defined the device_class for the humidity sensor.

Of course, you're spot on with the comment on outside/inside humidity, busy testing things out before I start buying sensors for inside.

Thanks for the quick reply, this works a treat. Perhaps the example below will help others who missed the device_class or naming convention.

My current config, running the latest 0.1.6-beta.
```
sensor:
  - platform: temperature_feels_like
    name: "Alex Room Feels Like Temp"
    source:
      - sensor.outside_humidity
      - sensor.alex_room_temperature
  - platform: template
    sensors:
      outside_humidity:
        value_template: "{{ state_attr('weather.home', 'humidity') }}"
        device_class: humidity
  - platform: mqtt
    state_topic: "tele/alexheater/SENSOR"
    name: "Alex Room Temperature"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.DS18B20.Temperature }}"
    device_class: temperature
```
